In [2]:
import numpy as np

**How to create an empty and a full NumPy array?**

In [3]:
arr=np.empty((3,3))
arr

array([[4.67296746e-307, 1.69121096e-306, 7.56595733e-307],
       [1.06811354e-306, 1.42419938e-306, 7.56603881e-307],
       [8.45603440e-307, 4.45046008e-307, 2.37667058e-312]])

**Create a Numpy array filled with all zeros**

In [6]:
arr=np.zeros((3,3),dtype='int')
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Create a Numpy array filled with all ones**

In [7]:
arr=np.ones((2,3),dtype='int')
arr

array([[1, 1, 1],
       [1, 1, 1]])

**Check whether a Numpy array contains a specified row**

In [10]:
arr=np.array([[2,2,1],[1,2,3]])
if [1,2,3] in arr.tolist():
    print("yes")
else:
    print("no")

if [1,1,1] in arr.tolist():
    print('yes')
else:
    print('no')

yes
no


**Remove single-dimensional entries from the shape of an array**

In [41]:
arr=np.arange(1,7)
arr=arr.reshape(1,2,3)
print(arr)
arr2=arr.reshape(2,3)
print(arr2)

[[[1 2 3]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]]


**Find the number of occurrences of a sequence in a NumPy array**

In [54]:
arr=np.arange(1,7)
arr=arr.reshape(2,3)
count=0
CountList=[1,2,3]
for i in range(len(arr)):
    if CountList in arr[i]:
        count=count+1
print(count)

1


**Find the most frequent value in a NumPy array**

In [67]:
arr=np.array([1,2,3,2,2,2,1,1,4,6])
np.bincount(arr).argmax()

2

**Combining a one and a two-dimensional NumPy Array**

In [78]:
arr1=np.arange(1,21).reshape(1,20)
arr2=np.arange(1,21).reshape(2,10)
arr3=np.append(arr2,arr1)
arr3.shape

(40,)

**How to compare two NumPy arrays?**

In [87]:
arr1=np.arange(1,21).reshape(1,20)
arr2=np.arange(1,21).reshape(1,20)

compare=arr1==arr2
isequal=compare.all()
print(isequal)

True


**Flatten a 2d numpy array into 1d array**

In [88]:
arr2=np.arange(1,21).reshape(2,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [89]:
arr3=arr2.flatten()
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


**Reverse a numpy array**

In [90]:
arr2=np.arange(1,21).reshape(2,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [92]:
np.flip(arr2)

array([[20, 19, 18, 17, 16, 15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])

In [93]:
np.transpose(arr2)

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19],
       [10, 20]])

**Get the maximum value from given matrix**

In [94]:
arr2=np.arange(1,21).reshape(2,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [96]:
arr2.max()

20

**Get the minimum value from given matrix**

In [97]:
arr2.min()

1

**Find the number of rows and columns of a given matrix using NumPy**

In [100]:
arr2.shape

(2, 10)

**Find the sum of values in a matrix**

In [101]:
arr2.sum()

210

**Calculate the sum of the diagonal elements of a NumPy array**

In [104]:
arr=np.array([[1,2],[2,4]])
np.trace(arr)

5

***Adding and Subtracting Matrices in Python ,Ways to add row/columns in numpy array,Matrix Multiplication in NumPy***

In [112]:
a=np.array([[1,2,3],[4,5,6],[54,3,2]])
b=np.array([[3,2,4],[3,2,7],[12,3,5]])
a+b

array([[ 4,  4,  7],
       [ 7,  7, 13],
       [66,  6,  7]])

In [113]:
a-b

array([[-2,  0, -1],
       [ 1,  3, -1],
       [42,  0, -3]])

In [114]:
a*b

array([[  3,   4,  12],
       [ 12,  10,  42],
       [648,   9,  10]])

In [115]:
a.shape

(3, 3)

In [116]:
b.shape

(3, 3)

In [120]:
c=a@b # Matrix Multiplication
c

array([[ 45,  15,  33],
       [ 99,  36,  81],
       [195, 120, 247]])

In [130]:
to_add=np.array([[9,9,9]])
np.append(c,to_add,axis=0)

array([[ 45,  15,  33],
       [ 99,  36,  81],
       [195, 120, 247],
       [  9,   9,   9]])

**Calculate the mean of array ignoring the NaN value**

In [144]:
arr=[[1,2,np.nan],[np.nan,2,3]]
arr2=np.nan_to_num(arr,0)

In [147]:
np.mean(arr2)

1.3333333333333333

In [148]:
np.mean(arr)

nan